#! /bin/bash

export VERSION="1"
export SYSTEM_DESC="KimeraKDE"
export SYSTEM_NAME="KimeraKDE"
export USERNAME="gamer"
export SIZE="10000MB"
export ARCHIVE_DATE=""
export WEBSITE=""
export DOCUMENTATION_URL=""
export BUG_REPORT_URL="https://github.com/ruineka/kimerakde/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export KERNEL_PACKAGE_ORIGIN="local"

export PACKAGES="\
	accountsservice \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	bluez \
	bluez-hid2hci \
	bluez-plugins \
	bluez-utils \
	broadcom-wl-dkms \
	cifs-utils \
	diffutils \
	dkms \
	dmidecode \
	dosbox \
	eog \
	epiphany \
	ethtool \
	evtest \
	ffmpeg \
	file-roller \
	firejail \
	flatpak \
	fmt \
	fuse-zip \
	fuse2 \
	gamemode \
	git \
	gst-plugin-pipewire \
	haveged \
	htop \
	intel-gpu-tools \
	intel-media-driver \
	intel-ucode \
	intel-undervolt \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-gamemode \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-libva \
	lib32-libva-intel-driver \
	lib32-libva-mesa-driver \
	lib32-libva-vdpau-driver \
	lib32-mesa \
	lib32-mesa-vdpau \
	lib32-openal \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	lib32-vulkan-intel \
	lib32-vulkan-radeon \
	libcurl-gnutls \
	libidn11 \
	libva-intel-driver \
	libva-mesa-driver \
	libva-vdpau-driver \
	libxcrypt-compat \
	libxss \
	liquidctl \
	logrotate \
	lshw \
	mesa \
	mesa-demos \
	mesa-vdpau \
	nano \
	nautilus \
	networkmanager \
	nfs-utils \
	nss-mdns \
	openal \
	openssh \
	podman \
	plasma \
	plasma-wayland-session \
	pulsemixer \
	python \
	python-inotify-simple \
	retroarch \
	rsync \
	sddm \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	ttf-liberation \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	vulkan-intel \
	vulkan-radeon \
	wavpack \
	wget \
	which \
	wireplumber \
	wqy-zenhei \
	xdg-desktop-portal \
	xdg-desktop-portal-plasma \
	xdg-desktop-portal-wlr \
	xdg-user-dirs-gtk \
	xf86-video-amdgpu \
	xorg-server \
"

export PACKAGE_OVERRIDES="\
	https://github.com/ChimeraOS/linux-chimeraos/releases/download/v6.3.9-chos2/linux-chimeraos-6.3.9.chos2-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/linux-chimeraos/releases/download/v6.3.9-chos2/linux-chimeraos-headers-6.3.9.chos2-1-x86_64.pkg.tar.zst \
"

export AUR_PACKAGES="\
	ayaled \
	bcm20702a1-firmware \
	boxtron \
	chimeraos-device-quirks-git \
	downgrade \
	frzr \
	gamescope-plus \
	gamescope-session-git \
	handygccs-git \
	hhfc-git \
	lib32-gamescope-plus \
	nintendo-udev \
	opengamepadui-bin \
	opengamepadui-session-git \
	oxp-sensors-dkms-git \
	pikaur \
	python-vdf \
	r8152-dkms \
	retroarch-autoconfig-udev-git \
	rtl8812au-dkms-git \
	rtl8814au-dkms-git \
	rtl88x2bu-dkms-git \
	rtl8821au-dkms-git \
	rtw89-dkms-git \
	ryzenadj-git \
	ryzenadj-controller-git \
	rz608-fix-git \
	steam-removable-media-git \
	ttf-kanit \
	xpad-noone-dkms \
	xpadneo-dkms \
"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	bluetooth \
	bluetooth-workaround \
	fstrim.timer \
	handycon \
	haveged \
	lightdm \
	ryzenadj-controller \
	sddm \
	sshd \
	systemd-timesyncd \
"

export USER_SERVICES="\
	gamemoded.service \
	ryzen-tctl \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
	" > /etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-lightdm
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
	" > /etc/sudoers.d/chimera

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	rm /usr/share/libalpm/hooks/70-dkms-install.hook
	rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	rm /usr/share/libalpm/hooks/71-dkms-remove.hook
	pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers

	# force -steamdeck option in desktop mode to prevent constant steam updates
	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop

}
